# Generated by Django 4.2.5 on 2023-09-26 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
