# Generated by Django 4.2.5 on 2023-09-25 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fulllname",
            new_name="fullname",
        ),
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="followee", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
