# Generated by Django 4.2.5 on 2023-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_fulllname_user_fullname_user_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(max_length=100),
        ),
    ]
