# Generated by Django 4.2.5 on 2023-09-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_fullname_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
